### ISSUE TITLE
graphic templates

### ISSUE THREAD

**Issue by rcb-hp3000** [shbatm/MMM-ISY#1]
Any possibility of getting a copy of the templates you used for the various electrical devices (plugs/lamps/ceiling fans/etc) - maybe included in the repo? Or a link to where they can be found?

**Comment by shbatm** [comment]
They're just SVG icons found mostly from https://iconify.design IIRC.

The majority of them should be in the example svg here: https://github.com/shbatm/MMM-ISY/blob/master/floorplan.svg.example
